baseURL = "https://s-horiguchi.github.io/"
title = "Shuhei A. Horiguchi"
languageCode = "en"
theme = "resume"
enableGitInfo = true
hasCJKLanguage = true

[params]
    firstName = "Shuhei A."
    lastName = "Horiguchi"
    address = "Kanazawa, Japan"

    profileImage = "/img/profile.jpeg"
    email = "shuhei.a.horiguchi@gmail.com"
    description = "Personal webpage of Shuhei A. Horiguchi"
    favicon = "/favicon.ico"
    topImage = "/img/pattern.svg"

    # what sections to display
    showSkills = false
    showProjects = true
    showOpenSource = false
    showPublications = true
    showExperience = true
    showEducation = true
    showQr = false
    showBlog = false
    showTopImage = true

[params.google]
    [params.google.analytics]
        trackerID = "UA-169625140-1"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/s-horiguchi/"

[[params.handles]]
    name = "Google-Scholar"
    link = "https://scholar.google.com/citations?user=cqg6IUMAAAAJ"

[[params.handles]]
    name = "ORCiD"
    link = "https://orcid.org/0000-0002-8459-1914"

[[params.handlesImages]]
    name = "Researchmap"
    link = "https://researchmap.jp/shuhei_horiguchi?lang=en"
    image = "https://researchmap.jp/outline/img/researchmap130.gif"

[outputs]
    home = ["HTML", "JSON"]

[taxonomies]
    tag = "tags"
