baseURL = "https://s-horiguchi.github.io/"
title = "Shuhei A. Horiguchi"
languageCode = "en"
theme = "resume"
enableGitInfo = true
hasCJKLanguage = true

[params]
    firstName = "Shuhei A."
    lastName = "Horiguchi"
    address = "Kanazawa, Japan"

    profileImage = "img/profile.jpeg"
    email = "shuhei.horiguchi@outlook.com"
    description = "Personal webpage of Shuhei A. Horiguchi"
    favicon = "/favicon.ico"

    # what sections to display
    showSkills = false
    showProjects = true
    showOpenSource = false
    showPublications = true
    showExperience = true
    showEducation = true
    showQr = false
    showBlog = false

[params.google]
    [params.google.analytics]
        trackerID = "UA-169625140-1"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/s-horiguchi/"

[[params.handles]]
    name = "Facebook"
    link = "https://facebook.com/horiguchi.shuhei"

[[params.handles]]
    name = "Researchmap"
    link = "https://researchmap.jp/shuhei_horiguchi"

[outputs]
    home = ["HTML", "JSON"]

[taxonomies]
    tag = "tags"
